### ISSUE TITLE
Python throwing errors and not pulling data into collectd

### ISSUE THREAD

**Issue by nodenineinc** [exoscale/collectd-cloudstack#4]
### Hello.  Trying a new install of this module into a functioning collectd already running on a functioning CStack 4.5 manager.

I can verify API functionality via the 'cs' python module, so I know that the API, URL, and keys are all working correctly.  Now I just need a little help sorting out why this python module is puking when executed.

I've set verbose TRUE and get the following in syslog:
=====
May 19 13:21:52 ca1-csman2 collectd[11349]: Unhandled python exception in read callback: KeyError: 'vmstate'
May 19 13:21:52 ca1-csman2 collectd[11349]: Traceback (most recent call last):
May 19 13:21:52 ca1-csman2 collectd[11349]:   File "/usr/share/collectd/plugins/cloudstack.py", line 412, in read_callback
May 19 13:21:52 ca1-csman2 info = get_stats()
May 19 13:21:52 ca1-csman2 collectd[11349]:   File "/usr/share/collectd/plugins/cloudstack.py", line 223, in get_stats
May 19 13:21:52 ca1-csman2 if rootvolume['vmstate'] == 'Running':
May 19 13:21:52 ca1-csman2 collectd[11349]: KeyError: 'vmstate'
May 19 13:21:52 ca1-csman2 collectd[11349]: read-function of plugin `python.cloudstack' failed. Will suspend it for 20.000 seconds.
=====

For the 'keyerror' log, I have confirmed that the API does return the following data in a listVolumes command, which is what call I believe the module is trying to make when it's complaining:
=====
"vmstate": "Running",
=====
so I'm not quite sure what the module is upset about in regards to this piece.

I've also iterated through all the API calls issued in the get_stats routine, and they all return data when called via the 'cs' plugin.

I have noticed that none of the "logger('verb'" messages ever show up in syslog, even with "VERBOSE_LOGGING = True" set explicitly in the cloudstack.py module.

Any thoughts?

**Comment by marcaurele** [comment]
Can you provide a sample result of that call: `cs listVolumes type=ROOT`

**Comment by nodenineinc** [comment]
Absolutely.

Some values lightly obfuscated obviously, but here's a couple records.

-Chris

root@ca1-csman2:~# cs listVolumes type=ROOT
{
  "count": 94,
  "volume": [
    {
      "account": "admin",
      "created": "2017-02-02T15:26:16-0800",
      "destroyed": false,
      "deviceid": 0,
      "displayvolume": true,
      "domain": "ROOT",
      "domainid": "e266baa0-c41b-11e3-ad8d-eaa275a97baf",
      "hypervisor": "XenServer",
      "id": "8f81727d-431d-4010-9e47-896557132f4e",
      "isextractable": true,
      "name": "ROOT-2325",
      "path": "f875cd34-b6f9-4ae6-97d6-4eeb328ccec0",
      "provisioningtype": "thin",
      "quiescevm": false,
      "serviceofferingdisplaytext": "2GB RAM, 1x650MHz",
      "serviceofferingid": "3bb9df70-1c08-46d0-aa88-575400c8ed5b",
      "serviceofferingname": "Small",
      "size": 107374182400,
      "state": "Ready",
      "storage": "pri1-vol1-share2",
      "storageid": "cf47489e-ae30-3d80-91a0-aedfe7ab0f0a",
      "storagetype": "shared",
      "tags": [],
      "templatedisplaytext": "100GB Root Disk",
      "templateid": "59754298-b814-454a-a8cc-88078a746182",
      "templatename": "CentOS 6.5 64-bit",
      "type": "ROOT",
      "virtualmachineid": "15aff7ff-54b0-451e-a2f8-1f48112fb872",
      "vmdisplayname": "utility01",
      "vmname": "utility01",
      "vmstate": "Running",
      "zoneid": "b1bcd7ae-e108-4f5f-bfd3-223335e38fe4",
      "zonename": "us2"
    },
    {
      "account": "admin",
      "created": "2017-03-14T07:56:04-0700",
      "destroyed": false,
      "deviceid": 0,
      "displayvolume": true,
      "domain": "ROOT",
      "domainid": "e266baa0-c41b-11e3-ad8d-eaa275a97baf",
      "hypervisor": "XenServer",
      "id": "e5fe93ed-e843-4f6a-95e5-3b50af1053e6",
      "isextractable": false,
      "name": "ROOT-4664",
      "path": "9ca2c8ef-5277-467c-955e-c219ca10a7c7",
      "provisioningtype": "thin",
      "quiescevm": false,
      "serviceofferingdisplaytext": "4GB RAM, 2x1GHz CPU",
      "serviceofferingid": "26959f66-6e4e-4746-b1d7-f45106bd541f",
      "serviceofferingname": "Medium",
      "size": 107374182400,
      "state": "Ready",
      "storage": "pri1-vol1-share1",
      "storageid": "6ea9f012-aa06-3671-a2d1-62c39dc8bc49",
      "storagetype": "shared",
      "tags": [],
      "templatedisplaytext": "Windows Server 2008 R2 SP1",
      "templateid": "995682bb-fcf0-41b7-aae2-e0047605a448",
      "templatename": "Windows Server 2008 R2 SP1",
      "type": "ROOT",
      "virtualmachineid": "6faf6e3e-664b-4b4a-8f2e-970c9bbdec91",
      "vmdisplayname": "Windows-Server-2008-R2-64bit-BASE",
      "vmname": "Windows-Server-2008-R2-64bit-BASE",
      "vmstate": "Stopped",
      "zoneid": "b1bcd7ae-e108-4f5f-bfd3-223335e38fe4",
      "zonename": "us2"
    },

**Comment by marcaurele** [comment]
I would thing that one of the volume listed does not have a state (I cannot figure out why). Install "jq" in your python virtualenv and run this query to find out which one is missing the state attribute:

```
cs listVolumes type=ROOT listall=true fetch_list=true | jq '.[] | if .state then "" else "missing state for volume " + .id end'
```

**Comment by nodenineinc** [comment]
Here's the full output of that command string you requested.
Cheers,
-Chris

=====
root@ca1-csman2:~# cs listVolumes type=ROOT listall=true fetch_list=true
| jq '.[] | if .state then "" else "missing state for volume " + .id end'
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
root@ca1-csman2:~#
=====

**Comment by marcaurele** [comment]
I just realized I did a mistake in the line of code, the error is about a missing attribute "vmstate" and not "state. Here is the good one:
```
cs listVolumes type=ROOT listall=true fetch_list=true | jq '.[] | if .vmstate then "" else "missing vm state for volume " + .id end'`
```

And do you still have the error in collectd logs?

**Comment by nodenineinc** [comment]
Ah - gotcha, I see.

This definitely outputs a couple instances of 'missing vm statefor
volume' cropping up in this output.

=====
root@ca1-csman2:~# cs listVolumes type=ROOT listall=true fetch_list=true
| jq '.[] | if .vmstate then "" else "missing vm state for volume " +
.id end'
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
"missing vm state for volume "
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
"missing vm state for volume "
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
"missing vm state for volume "
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
root@ca1-csman2:~#

=====

I've manually examined the output and found 3 volumes that do not have
the following elements:
=====
    "vmdisplayname":
    "vmname":
    "vmstate":
=====

I'm following up and investigating why/how these became lingering
volumes, but these were all customer driven situations, so I'd wager
this situation could happen again.

While I was researching these I found that they were also causing errors
in the Cstack UI when I tried to examine their details, so I've done a
little DB surgery and removed these errant volume and volume_store_ref
records.  It appears that the collectd plugin is now executing without
error following a collectd restart.

I'll keep you posted if I start getting data-points in a moment, but it
looks like your hint may have helped lead to this finally being
resolved, so much thanks.

Cheers,
-Chris

**Comment by nodenineinc** [comment]
ok - collectd is trying to send data as I'm seeing the node and
cloudstack plugin showing up in graphite, but it doesn't seem to be
actually gathering metrics.

This log message is now present on the node running cloudstack and the
collectd plugin.
=====
May 24 12:10:34 ca1-csman2 jsvc.exec[8119]: WARN 
[c.c.a.d.ParamGenericValidationWorker] (catalina-exec-1:ctx-c7ec86a7
ctx-607d2e3f ctx-90402bc2) Received unknown parameters for command
listHosts. Unknown parameters : listall
May 24 12:10:34 ca1-csman2 jsvc.exec[8119]: WARN 
[c.c.a.d.ParamGenericValidationWorker] (catalina-exec-4:ctx-968476ee
ctx-2fdd3a2c ctx-850ecbc1) Received unknown parameters for command
listSystemVms. Unknown parameters : listall
May 24 12:10:34 ca1-csman2 jsvc.exec[8119]: WARN 
[c.c.a.d.ParamGenericValidationWorker] (catalina-exec-2:ctx-54673b36
ctx-41f42810 ctx-5693e5dd) Received unknown parameters for command
listZones. Unknown parameters : listall
=====

so we're definitely closer in that the plugin is executing, but it's
still having trouble actually generating datapoint values.

-Chris

**Comment by marcaurele** [comment]
This message about the unknown parameter in the request is not important as CloudStack will simply skip it. If collectd is running without throwing error messages in the log, the data are sent correctly. It takes a few runs to get the first dots depending on how you configured the graphite rrd store. Otherwise have a look with a `tcpdump` to see if the data are arriving on your graphite server.

**Comment by nodenineinc** [comment]
Thanks again for following up - my apologies for a late reply - I was
out of town briefly on holiday.

I've had the plugin running for a couple days now but it seems we're
still not receiving any metric data.  Collectd is sending some output,
as evidenced by the automatic presence of the data fields that are
received that should be present, but none of the points actually contain
any metric values.  It's as if the keys are being sent but no values.

I setup a wildcard match to graph anything/everything from the
cloudstack plugin so you can see what I'm talking about.  No data values
are getting sent.

See attached screenshot.

-Chris

**Comment by marcaurele** [comment]
My turn to be off for holidays.

If you can see the values with VERBOSE_LOGGING=True, then the values are sent correctly and I cannot help you more on that. The problem must by lying somewhere in your graphite/carbon installation/configuration.

Attachment in emails are not captured by github. You have to attach them in the web interface manually.
